spring.application.name=project

spring.datasource.url=jdbc:mysql://localhost:3306/spring?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=$Parola123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spunem lui Spring să ruleze schema.sql și data.sql chiar dacă NU este o bază de date embedded
spring.sql.init.mode=always

# Gestionarea conflictului cu Hibernate
spring.jpa.hibernate.ddl-auto=none

